# File generated by github.com/posener/goaction. DO NOT EDIT.


FROM golang:1.24-alpine3.22
RUN apk add git 

COPY . /home/src
WORKDIR /home/src
RUN go build -o /bin/action ./cmd/goaction

ENTRYPOINT [ "/bin/action" ]
